name: github-actions-test
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env var
        run: |
          echo FOO=bar >> $GITHUB_ENV
      - name: Run a one-line script
        run: echo $FOO
