name: github-actions-test
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env var
        run: |
          export FOO=bar
          echo "::set-env name=FOO::$FOO"
      - name: Run a one-line script
        run: echo $FOO
